import project1 from "../photo/project1.png";
import project1Website from "../photo/project1Website.png";
import project2 from "../photo/project2.png";
import project2Website from "../photo/project2Website.png";
import {
  faHtml5,
  faCss3Alt,
  faJs,
  faReact,
  faBootstrap,
} from "@fortawesome/free-brands-svg-icons";
const ProjectList = [
  {
    id: 1,
    img: project1,
    imgAllPages: project1Website,
    title: "Toyqo",
    liveMode: "https://aya-abdelsalam.github.io/toyqo/",
    code: "https://github.com/Aya-AbdElsalam/toyqo",
    lang: [faHtml5, faCss3Alt, faJs],
    pages: [
      "Register /Sign in",
      "Home",
      "Shop",
      "product details",
      "About",
      "Blogs",
      "Blog details",
      "FAQ",
      "Contact",
      "cart",
      "Check out",
      "Viewed items",
    ],
    pages_ar: [
      "التسجيل بالموقع /تسجيل الدخول",
      "الصفحه الرئيسية",
      "تسوق",
      "تفاصيل عن المنتج",
      "عننا",
      "مقالات",
      "تفاصيل عن المقال",
      "اسئلة",
      "تواصل",
      "العربة",
      "الدفع",
      "المنتجات التي تم رؤيتها",
    ],

    features: [
      "Add to cart",
      "Remove from cart",
      "Remove from Viewed Items Page",
      "Add comment",
      "Remove Comment",
    ],
    features_ar: [
      "الأضافة للعربة",
      "الحذف من العربة",
      "الحذف من المنتجات التي رؤيتها",
      "اضافة تعليق",
      "حذف تعليق",
    ],
    dataStorage: "Local storage",
    dataStorage_ar: " التخزين المحلي ",
  },
  {
    id: 2,
    img: project2,
    imgAllPages: project2Website,
    title: "Pizza",
    liveMode: "https://pizza-restaurant-react-bootstrap.netlify.app",
    code: "https://github.com/Aya-AbdElsalam/PizzaRestaurant",
    lang: [faHtml5, faCss3Alt, faReact, faBootstrap],
    pages: [
      "Home",
      "Menu",
      "About us",
      "Gallery",
      "Our team",
      "team details",
      "Events",
      "Event details",
      "Contact",
      "Cart",
    ],
    pages_ar: [
      "الصفحه الرئيسية",
      "قائمه الطعام",
      "عننا",
      "معرض الصور",
      "اعضاء الفريق",
      "تفاصيل عن اعضاء الفريق",
      "اسئلة",
      "الأحداث",
      "تفاصيل عن الحدث",
      "التواصل",
      "العربة",
    ],

    features: [
      "Add to cart",
      "Remove from cart",
      "filter items by search, price",
      "Sort items by price",
      "Product card with quick view",
    ],
    features_ar: [
      "الأضافة للعربة",
      "الحذف من العربة",
      " تصفية المنتجات باستخدام البحث و السعر",
      "ترتيب المنتجات تبعا للسعر ",
      "بطاقة المنتج مع عرض سريع ",
    ],
    dataStorage: "Local storage , session storage",
    dataStorage_ar: "تخزين الجلسة , التخزين المحلي ",
  },
];
export default ProjectList;
