import project1 from "../photo/project1.webp";
import project1Website from "../photo/project1Website.webp";
import project2 from "../photo/project2.webp";
import project2Website from "../photo/project2Website.webp";
import project3 from "../photo/project3.webp";
import project3Website from "../photo/project3Website.webp";
import mui from "../photo/mui.png";
import {
  faHtml5,
  faCss3Alt,
  faJs,
  faReact,
  faBootstrap,
} from "@fortawesome/free-brands-svg-icons";
const ProjectList = [
  {
    id: 1,
    img: project1,
    imgAllPages: project1Website,
    title: "Toyqo",
    liveMode: "https://aya-abdelsalam.github.io/toyqo/",
    code: "https://github.com/Aya-AbdElsalam/toyqo",
    lang: [faHtml5, faCss3Alt, faJs],
    pages: [
      "Register /Sign in",
      "Home",
      "Shop",
      "product details",
      "About",
      "Blogs",
      "Blog details",
      "FAQ",
      "Contact",
      "cart",
      "Check out",
      "Viewed items",
    ],
    pages_ar: [
      "التسجيل بالموقع /تسجيل الدخول",
      "الصفحه الرئيسية",
      "تسوق",
      "تفاصيل عن المنتج",
      "عننا",
      "مقالات",
      "تفاصيل عن المقال",
      "اسئلة",
      "تواصل",
      "العربة",
      "الدفع",
      "المنتجات التي تم رؤيتها",
    ],

    features: [
      "Add to cart",
      "Remove from cart",
      "Remove from Viewed Items Page",
      "Add comment",
      "Remove Comment",
    ],
    features_ar: [
      "الأضافة للعربة",
      "الحذف من العربة",
      "الحذف من المنتجات التي رؤيتها",
      "اضافة تعليق",
      "حذف تعليق",
    ],
    dataStorage: "Local storage",
    dataStorage_ar: " التخزين المحلي ",
  },
  {
    id: 2,
    img: project2,
    imgAllPages: project2Website,
    title: "Pizza",
    liveMode: "https://pizza-restaurant-react-bootstrap.netlify.app",
    code: "https://github.com/Aya-AbdElsalam/PizzaRestaurant",
    lang: [faHtml5, faCss3Alt, faReact, faBootstrap],
    pages: [
      "Home",
      "Menu",
      "About us",
      "Gallery",
      "Our team",
      "team details",
      "Events",
      "Event details",
      "Contact",
      "Cart",
    ],
    pages_ar: [
      "الصفحه الرئيسية",
      "قائمه الطعام",
      "عننا",
      "معرض الصور",
      "اعضاء الفريق",
      "تفاصيل عن اعضاء الفريق",
      "اسئلة",
      "الأحداث",
      "تفاصيل عن الحدث",
      "التواصل",
      "العربة",
    ],

    features: [
      "Add to cart",
      "Remove from cart",
      "filter items by search, price",
      "Sort items by price",
      "Product card with quick view",
    ],
    features_ar: [
      "الأضافة للعربة",
      "الحذف من العربة",
      " تصفية المنتجات باستخدام البحث و السعر",
      "ترتيب المنتجات تبعا للسعر ",
      "بطاقة المنتج مع عرض سريع ",
    ],
    dataStorage: "Local storage , session storage",
    dataStorage_ar: "تخزين الجلسة , التخزين المحلي ",
  },
  {
    id: 3,
    img: project3,
    imgAllPages: project3Website,
    title: "PROLAND",
    imgIcon: mui,
    liveMode: "https://proland-site.netlify.app/",
    code: "https://github.com/Aya-AbdElsalam/PROLAND",
    lang: [faReact],

    pages: [
      "Landing page contains [PRODUCT - FEATURES - REVIEWS - CONTACT]",
      "Admin panel contains [DASHBOARD - USERS - ORDERS - TEAM - PRODUCTS]",
    ],
    pages_ar: [
      "صفحه رئيسيه تحتوي علي [المنتجات - المميزات - التقييمات - تواصل ]",
      "لوحة الإدارة تحتوي على [لوحة التحكم - المستخدمون - الطلبات - الفريق - المنتجات]",
    ],

    features: [
      "Add a new member",
      "Remove member",
      "Edit member's information",
      "Add a new product",
      "Remove product",
      "Edit product's details",
    ],
    features_ar: [
      "إضافة عضو جديد",
      "إزالة عضو",
      "تعديل المعلومات الخاصه بالعضو",
      "إضافة منتج جديد",
      "حذف المنتج",
      "تعديل البيانات الخاصه بالمنتج",
    ],
    dataStorage: "https://prolanddata.onrender.com",
    dataStorage_ar: "https://prolanddata.onrender.com",
  },
];
export default ProjectList;
